server:
  port: 8082

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/DigitalMedia
        registration:
          gateway-api:
            provider: keycloak
            client-id: api-gateway
            client-secret: FUiOD2SuBG4GiTK1X3Ur1Di8WodzwK7c
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8082'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: moviesRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: billingRoute
          uri: lb://billing-service
          predicates:
            - Path=/bills/**
        - id: usersRoute
          uri: lb://users-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG