INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'client', 'courses/Java', 125,'2022-09-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'provider', 'courses/Java', 232,'2022-10-05');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'admin', 'courses/Java', 789,'2022-10-25');
